# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-04-02 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atriculos',
            new_name='Articulos',
        ),
    ]
